<?php
return array(
1 => array('name' => '国际综合', 'url' => 'http://play.cec-tv.com.cn/channel/cec-tv3.m3u8'),
2 => array('name' => '国际旅游', 'url' => 'http://play.cec-tv.com.cn/channel/cec-tv2.m3u8'),
3 => array('name' => '俄罗斯音乐', 'url' => 'http://rutv.gcdn.co/streams/1410_1272/720n/index.m3u8'),
4 => array('name' => '阿里郎', 'url' => 'http://amdlive.ctnd.com.edgesuite.net/arirang_1ch/smil:arirang_1ch/master.m3u8'),
5 => array('name' => '朝鲜中央', 'url' => 'http://tv.nknews.org/tvhls/stream.m3u8'),
6 => array('name' => '韩国KCTV', 'url' => 'http://119.77.96.184:1935/chn05/chn05/chunklist_w644291506.m3u8'),
7 => array('name' => '韩国UBC', 'url' => 'http://59.25.202.81:1935/live/UBCstream/chunklist_w1495115977.m3u8'),
8 => array('name' => '韩国卫视', 'url' => 'http://218.38.152.31:1935/klive/klive.stream/playlist.m3u8'),
9 => array('name' => '韩国儿童', 'url' => 'http://ebsonairios.ebs.co.kr/ebsutablet500k/_definst_/tablet500k/chunklist_w1965791004.m3u8'),
10 => array('name' => '法国英语', 'url' => 'http://static.france24.com/live/F24_EN_LO_HLS/live_web.m3u8'),
11 => array('name' => '俄罗斯IGITV', 'url' => 'http://hls-igi.cdnvideo.ru/igi/igi_hq/playlist.m3u8'),
12 => array('name' => '俄罗斯ТВTV', 'url' => 'http://hls-video01.cdnvideo.ru/video01/smil:video01.smil/chunklist_b4128000.m3u8'),
13 => array('name' => '美国新闻', 'url' => 'http://livestream.usatv.com/hls/m3u8/USARMENIA720.m3u8'),
14 => array('name' => '美国TV7', 'url' => 'http://tv7plus.com/hls/tv7_site.m3u8'),
15 => array('name' => '日本TOKYO', 'url' => 'http://movie.mcas.jp/mcas/gm2_2/chunklist.m3u8'),
16 => array('name' => '日本天气', 'url' => 'http://movie.mcas.jp/mcas/wn1_2/master.m3u8'),
17 => array('name' => '日本新闻', 'url' => 'https://n24-cdn-live.ntv.co.jp/ch01/index.m3u8'),
18 => array('name' => '日本声优', 'url' => 'http://www.uniqueradio.jp/agplayerf/hls/Active.m3u8'),
19 => array('name' => '日本GSTV', 'url' => 'https://gemstv.wide-stream.net/gemstv01/smil:gemstv01.smil/playlist.m3u8'),
20 => array('name' => '环球卫视', 'url' => 'http://live.cgtn.com/1000/prog_index.m3u8'),
21 => array('name' => 'CGTN', 'url' => 'https://news.cgtn.com/resource/live/english/cgtn-news.m3u8'),
22 => array('name' => '点掌财经', 'url' => 'http://cclive2.aniu.tv/live/anzb.m3u8'),
23 => array('name' => '日本NHK华语', 'url' => 'https://nhkw-zh-hlscomp.akamaized.net/ixxemlzk1vqvy44o/playlist.m3u8'),
24 => array('name' => '韩国EBS 少儿频道', 'url' => 'http://ebsonairios.ebs.co.kr/ebsutablet500k/tablet500k/playlist.m3u8'),
25 => array('name' => '韩国阿里郎WORLDworld', 'url' => 'http://amdlive.ctnd.com.edgesuite.net/arirang_1ch/smil:arirang_1ch.smil/playlist.m3u8'),
26 => array('name' => '韩国阿里郎WORLD', 'url' => 'http://amdlive.ctnd.com.edgesuite.net/arirang_1ch/smil:arirang_1ch/master.m3u8'),
27 => array('name' => '韩国KCTV', 'url' => 'http://119.77.96.184:1935/chn05/chn05/chunklist_w644291506.m3u8'),
28 => array('name' => 'CGTN 国际频道', 'url' => 'http://live.cgtn.com/1000/prog_index.m3u8'),
29 => array('name' => '中国环球', 'url' => 'http://live.cgtn.com/1000/prog_index.m3u8'),
30 => array('name' => '狗狗宠物', 'url' => 'http://video.blivenyc.com/broadcast/prod/2061/22/file-3192k.m3u8'),
31 => array('name' => '亚洲新闻', 'url' => 'https://d2e1asnsl7br7b.cloudfront.net/7782e205e72f43aeb4a48ec97f66ebbe/index_3.m3u8'),
32 => array('name' => '乌克兰M2 音乐频道', 'url' => 'http://live.m2.tv/hls3/stream.m3u8'),
33 => array('name' => '西班牙中国环球', 'url' => 'http://livees.cgtn.com/1000e/prog_index.m3u8'),
34 => array('name' => '意大利V2 音乐频道', 'url' => 'http://de1se01.v2beat.live/playlist.m3u8'),
35 => array('name' => 'Darcizzle电视', 'url' => 'http://tv7plus.com/hls/tv7_site.m3u8http://tv7plus.com/hls/tv7_site.m3u8'),
36 => array('name' => 'Docurama电视', 'url' => 'https://cinedigm.vo.llnwd.net/conssui/amagi_hls_data_xumo1234A-docuramaA/CDN/master.m3u8'),
37 => array('name' => 'Dance电视', 'url' => 'https://vcndstv.teleosmedia.com/stream/dstv/dstv/seglist_720p.m3u8'),

);
?>
