<?php
return array(
1 => array('name' => 'CCTV1高清', 'url' => 'http://ivi.bupt.edu.cn/hls/cctv1hd.m3u8'),
2 => array('name' => 'CCTV2高清', 'url' => 'http://ivi.bupt.edu.cn/hls/cctv2hd.m3u8'),
3 => array('name' => 'CCTV3高清', 'url' => 'http://ivi.bupt.edu.cn/hls/cctv3hd.m3u8'),
4 => array('name' => 'CCTV4高清', 'url' => 'http://ivi.bupt.edu.cn/hls/cctv4hd.m3u8'),
5 => array('name' => 'CCTV5高清', 'url' => 'http://ivi.bupt.edu.cn/hls/cctv5phd.m3u8'),
6 => array('name' => 'CCTV6高清', 'url' => 'http://ivi.bupt.edu.cn/hls/cctv6hd.m3u8'),
7 => array('name' => 'CCTV7高清', 'url' => 'http://ivi.bupt.edu.cn/hls/cctv7hd.m3u8'),
8 => array('name' => 'CCTV8高清', 'url' => 'http://ivi.bupt.edu.cn/hls/cctv8hd.m3u8'),
9 => array('name' => 'CCTV9高清', 'url' => 'http://ivi.bupt.edu.cn/hls/cctv9hd.m3u8'),
10 => array('name' => 'CCTV10高清', 'url' => 'http://ivi.bupt.edu.cn/hls/cctv10hd.m3u8'),
11 => array('name' => 'CCTV11高清(停播)', 'url' => 'http://ivi.bupt.edu.cn/hls/cctv11hd.m3u8'),
12 => array('name' => 'CCTV12高清', 'url' => 'http://ivi.bupt.edu.cn/hls/cctv12hd.m3u8'),
13 => array('name' => 'CCTV13高清', 'url' => 'http://ivi.bupt.edu.cn/hls/cctv13hd.m3u8'),
14 => array('name' => 'CCTV14高清', 'url' => 'http://ivi.bupt.edu.cn/hls/cctv14hd.m3u8'),
15 => array('name' => 'CCTV17高清', 'url' => 'http://ivi.bupt.edu.cn/hls/cctv17hd.m3u8'),
16 => array('name' => 'CGTN高清', 'url' => 'http://ivi.bupt.edu.cn/hls/cgtnhd.m3u8'),
17 => array('name' => 'CGTN DOC高清', 'url' => 'http://ivi.bupt.edu.cn/hls/cgtnhd.m3u8'),
18 => array('name' => 'CHC电影高清', 'url' => 'http://ivi.bupt.edu.cn/hls/chchd.m3u8'),
19 => array('name' => 'CCTV1清晰', 'url' => 'http://ivi.bupt.edu.cn/hls/cctv1.m3u8'),
20 => array('name' => 'CCTV2清晰', 'url' => 'http://ivi.bupt.edu.cn/hls/cctv2.m3u8'),
21 => array('name' => 'CCTV3清晰(停播)', 'url' => 'http://ivi.bupt.edu.cn/hls/cctv3.m3u8'),
22 => array('name' => 'CCTV4清晰', 'url' => 'http://ivi.bupt.edu.cn/hls/cctv4.m3u8'),
23 => array('name' => 'CCTV5清晰(停播)', 'url' => 'http://ivi.bupt.edu.cn/hls/cctv5p.m3u8'),
24 => array('name' => 'CCTV6清晰(停播)', 'url' => 'http://ivi.bupt.edu.cn/hls/cctv6.m3u8'),
25 => array('name' => 'CCTV7清晰', 'url' => 'http://ivi.bupt.edu.cn/hls/cctv7.m3u8'),
26 => array('name' => 'CCTV8清晰(停播)', 'url' => 'http://ivi.bupt.edu.cn/hls/cctv8.m3u8'),
27 => array('name' => 'CCTV9清晰(停播)', 'url' => 'http://ivi.bupt.edu.cn/hls/cctv9.m3u8'),
28 => array('name' => 'CCTV10清晰', 'url' => 'http://ivi.bupt.edu.cn/hls/cctv10.m3u8'),
29 => array('name' => 'CCTV11清晰', 'url' => 'http://ivi.bupt.edu.cn/hls/cctv11.m3u8'),
30 => array('name' => 'CCTV12清晰', 'url' => 'http://ivi.bupt.edu.cn/hls/cctv12.m3u8'),
31 => array('name' => 'CCTV13清晰', 'url' => 'http://ivi.bupt.edu.cn/hls/cctv13.m3u8'),
32 => array('name' => 'CCTV14清晰(停播)', 'url' => 'http://ivi.bupt.edu.cn/hls/cctv14.m3u8'),
33 => array('name' => 'CCTV15清晰', 'url' => 'http://ivi.bupt.edu.cn/hls/cctv15.m3u8'),
34 => array('name' => 'CGTN清晰', 'url' => 'http://ivi.bupt.edu.cn/hls/cctv16.m3u8'),
35 => array('name' => 'CCTV17清晰', 'url' => 'http://ivi.bupt.edu.cn/hls/cctv17.m3u8'),
36 => array('name' => 'CHC家庭影院(未开启)', 'url' => 'rtmp://ivi.bupt.edu.cn:1935/livetv/chctv'),

);
?>
